Recode startup join timeout
Kamesuta/BungeePteroPower pull request #7
Opened 2024-02-05 18:51 UTC by Lefraudeur

Changes almost nothing, but makes more sense to code it like that

2024-02-06 04:14 UTC, Kamesuta requested changes

2024-02-06 04:14 UTC, Kamesuta commented on src/main/java/com/kamesuta/bungeepteropower/ServerController.java
> +                    plugin.getProxy().getScheduler().schedule(plugin, ()->player.connect(serverInfo), 5, TimeUnit.SECONDS);
The value of 5 seconds may vary depending on the server. Therefore, it is better to make it into a config file.

2024-02-06 07:58 UTC, Lefraudeur commented on src/main/java/com/kamesuta/bungeepteropower/ServerController.java
> +                    plugin.getProxy().getScheduler().schedule(plugin, ()->player.connect(serverInfo), 5, TimeUnit.SECONDS);
Done in 5e018d5e7a58099936979a5d3c62fd96290b4048

2024-02-07 02:16 UTC, Kamesuta commented
Thanks for PR! I'll merge soon.

2024-02-07 02:17 UTC, Kamesuta commented on src/main/java/com/kamesuta/bungeepteropower/ServerController.java
> +                    plugin.getProxy().getScheduler().schedule(plugin, ()->player.connect(serverInfo), 5, TimeUnit.SECONDS);
Perfect!

2024-02-07 02:18 UTC, merged